// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: hl7-server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HL7Service_SendMessage_FullMethodName = "/hl7Server.HL7Service/SendMessage"
)

// HL7ServiceClient is the client API for HL7Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HL7ServiceClient interface {
	SendMessage(ctx context.Context, in *HL7Message, opts ...grpc.CallOption) (*HL7Message, error)
}

type hL7ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHL7ServiceClient(cc grpc.ClientConnInterface) HL7ServiceClient {
	return &hL7ServiceClient{cc}
}

func (c *hL7ServiceClient) SendMessage(ctx context.Context, in *HL7Message, opts ...grpc.CallOption) (*HL7Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HL7Message)
	err := c.cc.Invoke(ctx, HL7Service_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HL7ServiceServer is the server API for HL7Service service.
// All implementations must embed UnimplementedHL7ServiceServer
// for forward compatibility.
type HL7ServiceServer interface {
	SendMessage(context.Context, *HL7Message) (*HL7Message, error)
	mustEmbedUnimplementedHL7ServiceServer()
}

// UnimplementedHL7ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHL7ServiceServer struct{}

func (UnimplementedHL7ServiceServer) SendMessage(context.Context, *HL7Message) (*HL7Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedHL7ServiceServer) mustEmbedUnimplementedHL7ServiceServer() {}
func (UnimplementedHL7ServiceServer) testEmbeddedByValue()                    {}

// UnsafeHL7ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HL7ServiceServer will
// result in compilation errors.
type UnsafeHL7ServiceServer interface {
	mustEmbedUnimplementedHL7ServiceServer()
}

func RegisterHL7ServiceServer(s grpc.ServiceRegistrar, srv HL7ServiceServer) {
	// If the following call pancis, it indicates UnimplementedHL7ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HL7Service_ServiceDesc, srv)
}

func _HL7Service_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HL7Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HL7ServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HL7Service_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HL7ServiceServer).SendMessage(ctx, req.(*HL7Message))
	}
	return interceptor(ctx, in, info, handler)
}

// HL7Service_ServiceDesc is the grpc.ServiceDesc for HL7Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HL7Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hl7Server.HL7Service",
	HandlerType: (*HL7ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _HL7Service_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hl7-server.proto",
}
